### ISSUE TITLE
V0.3.2 doesn't work.

### ISSUE THREAD

**Issue by drstrangelooker** [gha-utilities/init-pull-request#235]
**Describe the bug**

**To Reproduce**

1. Script with arguments, eg `deep_thought.sh --calculate-the-ultimate-question`

2. Please format multi-line output with triple back-ticks, eg...

```bash
Download action repository 'gha-utilities/init-pull-request@v0.3.2' (SHA:5d95f07a7eaa2a304475857fc24543761b79b7b8)
Error: Could not find file '/home/runner/work/_actions/_temp_e6f18f10-f6d6-4406-97eb-af0c31e9391c/_staging/gha-utilities-init-pull-request-5d95f07/node_modules/.bin/tsc'.
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

 - OS: [e.g. Debian]

 - Version [e.g. 0.0.1]

**Smartphone (please complete the following information):**

 - Device: [e.g. Android]

 - OS: [e.g. Nugget]

 - Then fill in Linux related information

**Additional context**

**Comment by S0AndS0** [comment]
Thanks for reporting!

When ya get a chance I'll need a bit more context please;

- What errors , if any, are shown?

- Are ya able to share a link to Action logs?

- Do a previous version function for your repository Workflow?

Example Workflow snip

```yaml
on:
  push:
    branches:
      - src-pages

jobs:
  jekyll_build:
      # ... Other steps here

      - name: Initialize Pull Request
        uses: gha-utilities/init-pull-request@v0.3.1
        with:
          verbose: true
          pull_request_token: ${{ secrets.GITHUB_TOKEN }}
          head: pr-pages
          base: gh-pages
          title: 'Updates site files from latest Actions build'
          body: >
            Perhaps a multi-line description
            about latest features and such.
```
