### ISSUE TITLE
Failed to initialize Pull Request

### ISSUE THREAD

**Issue by abrkn** [gha-utilities/init-pull-request#5]
```
Run gha-utilities/init-pull-request@v0.0.7
  with:
    pull_request_token: ***
    head: release-0.0.2
    base: master`
    title: Release v0.0.2
    body: Perhaps a multi-line description about latest features and such.
  
Failed to initialize Pull Request
Please check that your Workflow file looks similar to...
  - name: Initialize Pull Request
    uses: gha-utilities/init-pull-request
    with:
      pull_request_token: ${{ secrets.PULL_REQUEST_TOKEN }}
      head: feature-branch
      base: master
      title: Adds awesome feature
      body: >
        Some thing can now be done that could
        not be done before.
(node:2777) UnhandledPromiseRejectionWarning: HttpError: Validation Failed: {"resource":"PullRequest","field":"base","code":"invalid"}
    at /home/runner/work/_actions/gha-utilities/init-pull-request/v0.0.7/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2777) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2777) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by S0AndS0** [comment]
Initial thoughts are that line [`121` of `index.js`](https://github.com/gha-utilities/init-pull-request/blob/master/index.js#L121) is catching and re-throwing a `Validation Failed` error...


```
HttpError: Validation Failed: {"resource":"PullRequest","field":"base","code":"invalid"}
```


... generally this can be resolved for repositories that your account has write permissions by literally using `${{ secrets.PULL_REQUEST_TOKEN }}` as the `pull_request_token`, because GitHub automatically fills in that variable.


Looking closely at the Action snip there's an extra back-tic too, so it may be a good idea to double-check the `base` field


These two suggestions combined may look a bit like...


```
- name: Initialize Pull Request
  uses: gha-utilities/init-pull-request@v0.0.7
  with:
    pull_request_token: ${{ secrets.PULL_REQUEST_TOKEN }}
    head: release-0.0.2
    base: master
    title: Release v0.0.2
    body: Perhaps a multi-line description about latest features and such.
```


The `UnhandledPromiseRejectionWarning` could be fixed were I a bit more clever with encapsulating `octokit.pulls.create(...)` asynchronous calls, however, as this seems to only happen when errors are _bubbled-up_ getting cleverer hasn't been immediately necessary.


Please let me know if fixing the `Validation Failed` (which I believe to be the root cause) resolves the `UnhandledPromiseRejectionWarning` behavior. In the mean-time I'll be having a ponder about how to better synchronize calls to Octokit's asnync function.

**Comment by abrkn** [comment]
If you add a handler for process.on('unhandledPromiseRejection') that does `error => setImmediate(() => { throw error; }` then the action will fail properly.

**Comment by S0AndS0** [comment]
Thank you!

Version `v0.0.8` _should_ fully incorporate your suggestions and fix this bug; new example Action snip will likely be similar to...


```
- name: Initialize Pull Request
  uses: gha-utilities/init-pull-request@v0.0.8
  with:
    pull_request_token: ${{ secrets.PULL_REQUEST_TOKEN }}
    head: release-0.0.2
    base: master
    title: Release v0.0.2
    body: Perhaps a multi-line description about latest features and such.
```


... Related changes are lines [`112` - `133` of `index.js`](https://github.com/gha-utilities/init-pull-request/blob/a1db2987b1906cd8e478bec8d29b1e36fbd957ef/index.js#L112-L133), feel free to close this Issue if things both look good and function properly.

**Comment by abrkn** [comment]
I made an alternative to get around my issues here: https://github.com/abrkn/create-pull-request/blob/master/src/main.ts

**Comment by S0AndS0** [comment]
Excellent that you've found a solution, and that's some very succinct code. However, I'm still a bit perplexed on what the root cause of the errors where.

Does your usage of `octokit.pulls.create` somehow avoid the original _`Validation failed`_ error that was popping when using this Action?

**Comment by abrkn** [comment]
I was unable to use your code due to the silent failing. The way I do it is a fork of the official example code.

**Comment by S0AndS0** [comment]
I'm willing to review the whole Workflow that generated the `Validation Failed` error you've reported, because I'm not certain what ya mean by silent failing as the OP of this Issue contains the error that triggered the other warnings...


```
HttpError: Validation Failed: {"resource":"PullRequest","field":"base","code":"invalid"}
```


... _zooming-in_ further on this error exposes that more than likely the `"code":"invalid"` portion of this message is what caused the failure state.


Granted that error was a bit obfuscated by the `UnhandledPromiseRejectionWarning` and `DeprecationWarning` errors/warnings, but on the whole failing to validate to GitHub's service generates verbose error messages.


---


If ya mean that your Workflow was running other Actions even when this one had exited with a non-zero status code, then it may be worth configuring;


- [`jobs.<job_id>.strategy.fail-fast`](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) _"When set to true, GitHub cancels all in-progress jobs if any `matrix` job fails. Default: `true`"_

> While documentation states the default is `true`, it may be worth double checking that it's not set to `false` and/or explicitly setting to `true` becase that may mitigate future GitHub Action behavior changes from breaking things.

- [`jobs.<job_id>.strategy.max-parallel`](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel) _"The maximum number of jobs that can run simultaneously when using a matrix job strategy. By default, GitHub will maximize the number of jobs run in parallel depending on the available runners on GitHub-hosted virtual machines."_

> If other workflows and/or jobs are dependent upon sequential execution of Actions it is a good idea to set this to `1`, because that'll prevent race conditions and ensure things terminate upon any errors... Though if I remember correctly there is another way to define that one Workflow is dependent upon another finishing without errors.

- [`jobs.<job_id>.steps.continue-on-error`](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) _"Prevents a job from failing when a step fails. Set to `true` to allow a job to pass when this step fails."_

> Set to `false` to ensure that an Action failing causes entire Job to fail.


... eg...


```YAML
jobs:
  jekyll_build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 1

    steps:
      continue-on-error: false

      # Pull, make changes, and commit stuff here...

      - name: Initialize Pull Request
        uses: gha-utilities/init-pull-request@v0.1.1
        with:
          verbose: true
          debug: true
          pull_request_token: ${{ secrets.GITHUB_TOKEN }}
          head: pr-pages
          base: gh-pages
          title: 'Updates site files from latest Actions build'
          body: Description about latest features and such.
```
